### ISSUE TITLE
Custom ports for Database on self deployments

### ISSUE THREAD

**Issue by markoftw** [checkmarble/marble-backend#475]
Hi, there seems to be an issue when using custom ports for the database, especially for non-development environments.

Related links:

https://github.com/checkmarble/marble-backend/blob/main/repositories/postgres/postgres.go#L45-L50
https://github.com/checkmarble/marble-backend/blob/main/utils/database.go#L19

Is there a specific reason for it?

**Comment by Pascal-Delange** [comment]
Hi @markoftw ,
Thanks for reaching out !
Your are right, this does not seem correct. It does work four out managed cloud offering (since we're connecting the server to the DB through a unix socket, see why [here](https://cloud.google.com/sql/docs/postgres/connect-run)), but does not work in the general case.
I pushed a PR to correct this issue.
